# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('organization', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('IR', 'Initial Request'), ('CF', 'Event Confirmed'), ('ED', 'Event Declined'), ('EX', 'Event Canceled'), ('EC', 'Event Completed')], default='IR', max_length=2)),
                ('head_count', models.IntegerField(blank=True)),
                ('open_to_public', models.BooleanField()),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msevents.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventDateLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventdate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msevents.EventDate')),
            ],
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msevents.Event')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(default='Microsoft Space', max_length=160)),
                ('room', models.CharField(max_length=160)),
                ('details', models.TextField(blank=True, max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('EO', 'Event Organizer'), ('GK', 'Gate Keeper'), ('AD', 'Administrator')], default='EO', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eventdatelocation',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msevents.Location'),
        ),
    ]
