# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msevents', '0002_auto_20170320_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='head_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventrole',
            name='name',
            field=models.CharField(default='Gate Keeper', max_length=160),
        ),
    ]
