# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msevents', '0003_auto_20170425_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdatelocation',
            name='eventdate_id',
        ),
        migrations.RemoveField(
            model_name='eventdatelocation',
            name='location_id',
        ),
        migrations.AddField(
            model_name='eventdate',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msevents.Location'),
        ),
        migrations.DeleteModel(
            name='EventDateLocation',
        ),
    ]
